In [24]:
import numpy as np
i = 1
j = 2
x = np.array([i, j])

i = 3
j = 4

x = np.append([x], [[i, j]], axis = 0)
print (x)

print ('\n')

y = np.append([x], [[i, j]], axis = 0)
print (y)

[[1 2]
 [3 4]]




ValueError: all the input arrays must have same number of dimensions

In [25]:
import numpy as np
i = 1
j = 2
x = np.array([i, j])

i = 3
j = 4

x = np.vstack((x, [i, j]))
print (x)

x = np.vstack((x, [i, j]))
print (x)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [3 4]]


In [34]:
list = [[1, 2]]
list.append([5, 6])
list.append([3, 4])
#list.sort()
print (list)

[[1, 2], [5, 6], [3, 4]]


In [43]:
import operator
dict = {}
dict[1] = 2 
dict[5] = 1 
dict[3] = 4 
sorted_dict = sorted(dict.items(), key=operator.itemgetter(1))
sorted_dict

[(5, 1), (1, 2), (3, 4)]

In [1]:
### lamda
# ref: http://falldog7.blogspot.tw/2009/07/python-lambda.html

def func(x, y, z):
    return x + y + z
print(func(1, 2, 3))

# the same as
func2 = lambda x,y,z : x+y+z
print(func2(1, 2, 3))

6
6


In [7]:
### lamda
def edit_story(words, func):
    for word in words:
        print(func(word))
        
stairs = ['aaa', 'bbb', 'ccc', 'ddd']

def enliven(word):
    return word.capitalize() + '!'

print(edit_story(stairs, enliven))
# the same as
print(edit_story(stairs, lambda word: word.capitalize() + '!'))

Aaa!
Bbb!
Ccc!
Ddd!
None
Aaa!
Bbb!
Ccc!
Ddd!
None


In [8]:
### VariableScope

x = 10
def outer():
   x = 100         # 這是在 outer() 函式範圍的 x
   def inner():
       nonlocal x
       x = 1000    # 改變的是 outer() 函式的 x
   inner()
   print(x)        

outer()            # 顯示 1000
print(x)           # 顯示 10

1000
10


In [9]:
### yield
### http://blog.blackwhite.tw/2013/05/python-yield-generator.html
### https://openhome.cc/Gossip/Python/YieldGenerator.html

def myrange(n):
    x = 0
    while True:
        yield x
        x += 1
        if x == n:
            break

for i in myrange(10):
    print(i, end='')
print()

0123456789


In [15]:
### class definition
class Account:
    def __init__(self, number, name):
        self.number = number
        self.name = name
        self.balance = 0
        
    def deposit(self, amount):
        if amount <= 0:
            raise ValueError('must be positive')
        self.balance += amount
        
    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount
        else:
            raise RuntimeError('balance not enough')
            
acct = Account('123-456-789', 'Justin')
print(acct.number)    # 123-456-789
print(acct.name)      # Justin

acct1 = Account('123-456-789', 'Jenny')
deposit1 = acct1.deposit
withdraw1 = acct1.withdraw
deposit1(100)
withdraw1(50)
print(acct1.balance)

acct2 = Account('987-654-321', 'Weber')
deposit2 = acct2.deposit
withdraw2 = acct2.withdraw
deposit2(200)
withdraw2(100)
print(acct2.balance)

acct1.deposi = acct2.deposit
acct1.deposi(1000)      # 你其實是將錢存到 acct2 去
deposit1(200)
print(acct1.balance)     # 50
print(acct2.balance)     # 1100


123-456-789
Justin
50
100
250
1100


In [19]:
### @staticmethod v.s. @classmethod
# http://blog.csdn.net/handsomekang/article/details/9615239
# @staticmethod不需要表示自身对象的self和自身类的cls参数，就跟使用函数一样。
# @classmethod也不需要self参数，但第一个参数需要是表示自身类的cls参数。
# 如果在@staticmethod中要调用到这个类的一些属性方法，只能直接类名.属性名或类名.方法名。
# 而@classmethod因为持有cls参数，可以来调用类的属性，类的方法，实例化对象等，避免硬编码

# https://zhuanlan.zhihu.com/p/28010894
# 如果希望在方法裡面调用静态类，那么把方法定义成类方法是合适的，
# 因为要是定义成静态方法，那么你就要显示地引用类A，这对继承来说可不是一件好事情。
'''
class A:

    @staticmethod
    def m1()
        pass

    @staticmethod
    def m2():
        A.m1() # bad

    @classmethod
    def m3(cls):
        cls.m1() # good
'''



class A(object):  
    bar = 1  
    def foo(self):  
        print ('foo')  
 
    @staticmethod  
    def static_foo():  
        print ('static_foo')  
        print (A.bar)  
 
    @classmethod  
    def class_foo(cls):  
        print ('class_foo')  
        print (cls.bar)  
        cls().foo()  
  
A.static_foo()  
A.class_foo()  

static_foo
1
class_foo
1
foo
